### ISSUE TITLE
enemy combat priority

### ISSUE THREAD

**Issue by PhiGam** [lobobeebe/PixelMoba#18]
Enemies do not target walls.  Instead walls just get in the way of enemy's locked target, until they are destroyed.

**Comment by lobobeebe** [comment]
Can you explain this one? Are they currently targeting walls?

**Comment by PhiGam** [comment]
They are not targeting walls.  Sorry if that was misleading! I was trying to get a different idea across, but it didnt make sense and Ive changed my mind anyway. 
 Just scrap this ticket.
