### ISSUE TITLE
New floor tiles and obstacle

### ISSUE THREAD

**Issue by PhiGam** [lobobeebe/PixelMoba#19]
Replace floor tiles with any of these.  Unsure if u can easily add all 4 scattered randomly.  Doesn't really matter as of now.

Also added a tree.  Superimpose tree on any woodland tile.  Tree should block player/bullet
![Woodland](https://user-images.githubusercontent.com/70117169/91624531-e839d500-e96e-11ea-83ca-12736d5a67eb.png)
 movement.

**Comment by lobobeebe** [comment]
Done
